### ISSUE TITLE
feat(config): throw on invalid config instead of using fallback

### ISSUE THREAD

**Issue by Aghassi** [JamieMason/syncpack#111]
## Description

I believe, and I could be wrong, that when the config read (specifically in the case of a `.js` config) is malformed, syncpack falls back on and uses a default config. The reason that I think this is the wrong solution is because it can lead to scenarios where in syncpack passes when it should instead fail.

## Suggested Solution

If syncpack.config.js fails for any reason (like missing dependencies in my case due to uninstalled node_modules), syncpack needs to bubble up that error and exit with code 1 to inform me that the config is malformed. This would have prevent a large headache for me of trying to figure out why syncpack was running but not failing.

## Help Needed

Just confirmation that the behavior I described above is intended and if it is ok with being improved

**Comment by JamieMason** [comment]
Hey @Aghassi, that's right. 

1. The config file is read on this line:
   
   https://github.com/JamieMason/syncpack/blob/13e6c70ae1f4eefddb93f77a83bb02915a426dfc/src/lib/get-input/get-config.ts#L33
1. `.js` config files are read using [cosmicconfig](https://github.com/davidtheclark/cosmiconfig) on this line:
   
   https://github.com/JamieMason/syncpack/blob/13e6c70ae1f4eefddb93f77a83bb02915a426dfc/src/lib/disk.ts#L38
1. If the `.js` config file throws or isn't found then an empty object is returned by `disk.readConfigFileSync`.
1. The rest of that [`getConfig`](https://github.com/JamieMason/syncpack/blob/13e6c70ae1f4eefddb93f77a83bb02915a426dfc/src/lib/get-input/get-config.ts#L24) function then attempts to read each config value and **uses it only if it's valid**, otherwise using a default if missing or invalid.

## Possible Approach

There is currently some undocumented logging which can be enabled like so

```shell
SYNCPACK_VERBOSE=true syncpack # list/format/fix-mismatches/etc
```

I think what I'd want to do is:

1. Add/update logs to make better use of log levels (in descending order of amount: debug, info, warn, error, silent).
1. Set the default log level to `error`, so that errors start appearing in output for everyone.
1. Expose a `logLevel` in config so that it can be set to `silent` if needed, to return to how it works today.
1. Remove `SYNCPACK_VERBOSE` and make use of the above.

Notes/Questions:

1. Not being able to find a config file **is not** an error.
1. cosmiconfig finding a config file but it being malformed **is** an error.
1. Does cosmiconfig let us tell the difference? (I've not checked the docs yet).
1. The typical CLI output should probably not be affected by the logLevel – running `syncpack list` with `--log-level=silent'` and getting no output would be weird.

I like the idea but it's probably a low priority, compared to some of the other features coming up. 

Thanks a lot for this and your other issues, they've all helped improve syncpack a lot.

**Comment by Aghassi** [comment]
My pleasure! This tool has been invaluable in trying to keep things aligned while we scale and dedupe dependencies. Until or unless we have one `workspace` these things matter.

Per your questions:

>  1. Not being able to find a config file is not an error.
Agreed, having a default makes sense in this case.
>  2. cosmiconfig finding a config file but it being malformed is an error.
Agreed here too, because otherwise falling back on the default is confusing
>  3. Does cosmiconfig let us tell the difference? (I've not checked the docs yet).
Yes loading the config will `reject` a Promise, see here https://www.npmjs.com/package/cosmiconfig#explorerload
>  4. The typical CLI output should probably not be affected by the logLevel – running syncpack list with --log-level silent and getting no output would be weird.
To rephrase and I think agree, the result of the CLI should ignore the log level, but internal information around `debug` statements should show based on log level. If so then yes. Without adding another library you can rely on `debug` from `util` https://nodejs.org/api/util.html#utildebugsection. Then just set some env variable based on flag.

**Comment by JamieMason** [comment]
Released in [10.6.1](https://github.com/JamieMason/syncpack/releases/tag/10.6.1). Any problems, please let me know. 

If you find syncpack useful, please star the project or help us spread the word to other Developers.

**Comment by Aghassi** [comment]
Solid thanks! I still have to get us to 10.x. I have an issue with `rules_js` exiting with the incorrect error code and I haven't figured out why yet. Been busy. Will get there though! I'm looking forward to all the improvements :)

**Comment by JamieMason** [comment]
This version might help with that, I've reverted lint semver groups from erroring when it sees a non semver version, which I think I did in V10.

**Comment by Aghassi** [comment]
> This version might help with that, I've reverted lint semver groups from erroring when it sees a non semver version, which I think I did in V10.

Oh man that actually might be it! Ok I'll upgrade my diff internally and see. Very excited to take in the new features ❤️

**Comment by JamieMason** [comment]
You're welcome mate, which pnpm fix was it by the way?

**Comment by Aghassi** [comment]
@JamieMason `workspace:*` support, that fix :)
