### ISSUE TITLE
Syncpack replaces `workspace:*` with version number

### ISSUE THREAD

**Issue by Alxandr** [JamieMason/syncpack#121]
## Description

After upgrading to syncpack 9.0.2 (from 8.5.14) syncpack has suddenly started replacing my `workspace:*` versions with the concrete package version, which I do not want. I have `workspace: false` in the config, but it does not seem to help.

## Suggested Solution

Revert this to how it worked in < v9.  The `workspace:*` versions should be kept.

## Help Needed

I'm using PNPM workspaces.

**Comment by JamieMason** [comment]
Thanks @Alxandr 👍

**Comment by JamieMason** [comment]
I started looking into this @Alxandr but will need some more information from you.

There's a [test scenario](https://github.com/JamieMason/syncpack/blob/d397ea7d986815e3b5a79bcb017db83670839661/test/scenarios/mismatches-include-non-semver-versions.ts#L5-L9) which shows that this is expected behaviour. Can you tell me a bit more about your setup and the expected and actual behaviour? Then we can figure it out, maybe I've missed something I don't know.

**Comment by Alxandr** [comment]
What I have is the following:

```package.json
{
  "name": "@namespace/whatever",
  "dependencies": {
    "@namespace/tsconfig": "workspace:*"
  }
}
```

and I just want to (somehow, I'm OK with having to configure it) have syncpack ignore all dependencies where the version starts with `workspace:`. That's about it. I'm not entirely sure about how that matches with the `deps` syntax you use in the tests there. Basically, the idea is that `workspace:*` is guaranteed to be the correct version, because it uses the exact package version.

**Comment by JamieMason** [comment]
Got you, thanks.

**Comment by JamieMason** [comment]
Hopefully this is fixed by https://github.com/JamieMason/syncpack/releases/tag/9.1.2, please let me know of any problems.

**Comment by markmartirosian** [comment]
@JamieMason I think this is happening again

**Comment by webpro** [comment]
Also, when `workspace:*` is used in each package, `list-mismatches` reports as if they're not the same.

**Comment by webpro** [comment]
Willing to work on it, feel free to close or chime in: https://github.com/JamieMason/syncpack/pull/149

**Comment by JamieMason** [comment]
Mentioning a fix here from the discussion at #149.

```json
{
  "versionGroups": [
    {
      "packages": ["**"],
      "dependencies": ["each", "package", "name", "developed", "in", "this", "monorepo"],
      "dependencyTypes": ["dev"],
      "pinVersion": "workspace:*"
    }
  ]
}
```

Whenever a package developed in your monorepo is used in `devDependencies`, its version will be pinned at `workspace:*` (if a package didn't use it in the first place, it won't be added).

**Comment by JamieMason** [comment]
Another problem example here, need a fix and/or improved getting started guides to help with this 

https://github.com/mintterteam/mintter/commit/b15c9c9cb3fa230c56c2f1020a01178c166b40cf#diff-c94a275588709f8cb5ffda807da029027477098cdb2b8b77a3f8e962290b8202

/cc @burdiyan, apologies I would revert that commit

**Comment by apetta** [comment]
Similar problem in yarn workspaces with:
`'*'` being replaced with version number

**Comment by JamieMason** [comment]
This should be fixed in the next release, but will take a little while as it involves a big overhaul of the internals and tests.

**Comment by JamieMason** [comment]
@Alxandr Something I've just realised about your original comment, you mentioned `9.0.2` and `workspace: false` not working. 

#### Fix 1

That form of config was deprecated in [9.0.0](https://github.com/JamieMason/syncpack/releases/tag/9.0.0) (instructions in the release notes). If you update your config then you should be able to ignore local dependencies.

#### Fix 2

Another approach to fixing this is to tell syncpack that you don't want your packages to have identical exact versions (the default) but that `local` packages should be referenced using `"workspace": "*"` whenever they're used in say `devDependencies`.

(By omitting `peer` and `prod` for example, any local packages used in those places would continue to be enforced to be identical to the canonical `.version` property of each local package).

Use the following config to do that:

```json
{
  "versionGroups": [
    {
      "packages": ["**"],
      "dependencies": ["each", "package", "name", "developed", "in", "this", "monorepo"],
      "dependencyTypes": ["dev"],
      "pinVersion": "workspace:*"
    }
  ]
}
```

#161 will come in the next release to make this easier to manage, so it would become:

```json
{
  "versionGroups": [
    {
      "packages": ["**"],
      "dependencies": ["$LOCAL"],
      "dependencyTypes": ["dev"],
      "pinVersion": "workspace:*"
    }
  ]
}
```

#### Summary

If a given monorepo has deeper requirements to it than a monorepo-wide exact version policy, config will be needed to tell syncpack what and where those exceptions to the norm are.

I think this is actually the fix for this issue, as I don't think there is a universal policy which syncpack can adopt which would be suitable for every repo out there. I've gone with an exact single version policy as a sensible default, then the various kinds of version and semver group should allow you to tune various parts of it to suit any custom needs you have.

**I will close this issue on that basis, but please continue to ask questions or send suggestions**.

I really want to improve the docs and site but first is working on the next release which as mentioned above is a big job. Once done it should make it easier to support other kinds on non-semver versions such as git tags etc, but it'll take a while yet.

#### Finally

If anyone reading this finds syncpack useful, _please_ tell people about it – it's completely free and has been a ton of work, please help spread the word ❤️ Thanks!

**Comment by audunolsen** [comment]
> Similar problem in yarn workspaces with: `'*'` being replaced with version number

Is there any existing way to prevent syncpack from editing the version field of local workspace packages?

Just discovered syncpack, amazing work @JamieMason 🔥

**Comment by JamieMason** [comment]
Thanks @audunolsen.

> Is there any existing way to prevent syncpack from editing the version field of local workspace packages?

That's a _definite_ bug, if the version number such as `*` which is higher/newer than the `.version` of the source package it can end up winning out and replacing the .version which is obviously something that should never be allowed. 

The next release has tests that ensure this will not happen but for now I would go with Fix 1 and basically disable the `local` [`dependencyType`](https://jamiemason.github.io/syncpack/config/dependency-types).

You can do that by not including `local` in the array:

```json
{
  "dependencyTypes": ["dev", "prod"]
}
```

Or by excluding it like so: (from syncpack [11.2.1](https://github.com/JamieMason/syncpack/compare/10.9.3...11.2.1) only)

```json
{
  "dependencyTypes": ["!local"]
}
```

**Comment by audunolsen** [comment]
> Why does the array entries need to alias names of package.json fields?  Makes it a little hard to grok.
> ~~Maybe syncpack should support some kind of access control list for dependency types, so that you can deny or allow it to process certain fields.~~

Didn't know you could negate/exclude dependency with `!`, so that part of my edit was covered by your answer.

The first question was about what's the rationale for mapping special keywords to package.json fields? For me it wasn't particularly intuitive understanding e.g. `prod` meant `dependencies`. Not really relevant to the thread just curious.

**Comment by JamieMason** [comment]
[12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0) was just released today and with it is an overhaul to the documentation.

There is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide and [Local Package Versions](https://jamiemason.github.io/syncpack/guide/local-package-versions) guide which aim to improve understanding around the things we encountered in this issue.

Thanks everyone for your help.

**Comment by JamieMason** [comment]
👋  Just an FYI that as of v14 this workaround won't be needed any more, there is a new [`strict`](https://jamiemason.github.io/syncpack/config/strict/) config which is `false` by default. Syncpack will check that the workspace specifier **satisfies** the local version specifier – meaning `workspace:*` and `workspace:~` etc are basically always valid – it would only complain if eg: 

1. You had something like `workspace:1.0.0` but the local version is `2.0.0`
2. You used a workspace specifier, but the local package is missing a `version` property

It is still in alpha and there are some nits, but the docs have been rewritten for v14:

- [Getting Started](https://jamiemason.github.io/syncpack/)
- [Version Groups](https://jamiemason.github.io/syncpack/version-groups/)
