### ISSUE TITLE
How to configure different versions of the same dependency?

### ISSUE THREAD

**Issue by viocost** [JamieMason/syncpack#156]
## Description

Currently we are trying to fix a very messy code base, where half of workspaces have one version of a dependency, and another half have another version.

With current configuration, our only option is to manually add all workspaces with the dependency version x to a group x, and the same for version y, which is very tedious.

I'm not sure, if there is a way ignore by dependency version, so we could gradually migrate all workspaces without breaking anything? 

I've tried adding both `isIgnored` and `pinVersion` to the version group - and it didn't like it

Also, it seems that wildcard inclusive group has precedence over more specific rules, so if I write a rule to check all packages like this `["**"]`, the further rule for the same dependency and a `specific package` will not work. 

## Suggested Solution
1. Add priority by specificity, so specific packages will always win wildcard patterns
2. Add ignore version rule

**Comment by JamieMason** [comment]
Hi @viocost,
Could you share your configuration please? that will help me diagnose the problem. 

> Also, it seems that wildcard inclusive group has precedence over more specific rules, so if I write a rule to check all packages like this `["**"]`, the further rule for the same dependency and a `specific package` will not work. 

[Each dependency can only belong to one version group, the first group which matches a given dependency will apply.](https://jamiemason.github.io/syncpack/guide/version-groups#how-groups-are-assigned), it sounds like you were quite close to what you needed, but that first group you created which had `packages: ["**"]` sounds like it might have been too greedy/broad/general.

I can't see any of your code so this could be wrong, but your situation sounds a lot like the [example use case in the docs](https://jamiemason.github.io/syncpack/guide/version-groups), you could be able to define a version group for just this one problem dependency, and list all of the packages which are stuck on that version.

```json
{
  "versionGroups": [
    {
      "label": "These packages are stuck on uh-oh@11 for now",
      "dependencies": ["uh-oh"],
      "packages": ["@stricken/server", "@stricken/ui"]
    }
  ]
}
```

That will define that one half of your repo you mentioned, with the other half being part of the default version group.

Hopefully this makes sense, like I said I'm flying a bit blind here but please hit me back with some more information 👍🏻

The new features you mentioned won't be needed.

**Comment by JamieMason** [comment]
As you mentioned in the OP, syncpack will complain that you must choose either `pinVersion` or `isIgnored` so it is sure what your intentions are. Since we spoke did you find a configuration that gives you what you need? I can try to help some more. Did you try [my suggestion here](https://github.com/JamieMason/syncpack/issues/156#issuecomment-1690268385) to split your repo in half? You will probably need one version group for version X that you need to be stuck on, with the rest going in the default version group.

With your repo being messy, your syncpack configuration might also be a little messy/verbose to account for everything you need. As your situation improves, your syncpack config should also reduce in size.
