### ISSUE TITLE
Question: how to have a dependency in both peer and dev?

### ISSUE THREAD

**Issue by crfrolik** [JamieMason/syncpack#225]
My config:

```json
{
  "semverGroups": [
    {
      "label": "dev dependencies are ~ prefixed",
      "range": "~",
      "dependencyTypes": ["dev"],
      "dependencies": ["**"],
      "packages": ["**"]
    },
    {
      "label": "prod and peer dependencies are ^ prefixed",
      "range": "^",
      "dependencyTypes": ["prod", "peer"],
      "dependencies": ["**"],
      "packages": ["**"]
    }
  ]
}
```

This works fine except I want to have a dependency `foo` that's in both `devDependencies` and `peerDependencies`:

```json
{
  "devDependencies": {
    "foo": "~1.0.0"
  },
  "peerDependencies": {
    "foo": "^1.0.0"
  }
}
```

`syncpack lint` gives an error for this.

```
= Default Version Group ========================================================
✘ foo ~1.0.0 → ^1.0.0 package.json > devDependencies [HighestSemverMismatch]
```

How can I configure this so lint won't complain?

**Comment by JamieMason** [comment]
Hi @crfrolik, this is because they are in the same [Version Group](https://jamiemason.github.io/syncpack/guide/getting-started/#version-mismatches). 

Syncpack needs teaching about the rules of your project if you do not have a monorepo-wide single version policy. The [Start Small](https://jamiemason.github.io/syncpack/guide/getting-started/#start-small) section of the Getting Started guide I think is relevant here.

If you move one of them into a separate group then they will no longer be compared. There are lots of ways you might choose to organise your project, and the best way will be up to you, but the simplest example that would fix this specific case might be to mirror how you are slicing the project by semver range rules:

```json
{
  "semverGroups": [
    {
      "label": "dev dependencies are ~ prefixed",
      "range": "~",
      "dependencyTypes": ["dev"],
      "dependencies": ["**"],
      "packages": ["**"]
    },
    {
      "label": "prod and peer dependencies are ^ prefixed",
      "range": "^",
      "dependencyTypes": ["prod", "peer"],
      "dependencies": ["**"],
      "packages": ["**"]
    }
  ],
  "versionGroups": [
    {
      "label": "dev dependencies should use the same version",
      "range": "~",
      "dependencyTypes": ["dev"]
    },
    {
      "label": "prod and peer dependencies should use the same version",
      "dependencyTypes": ["prod", "peer"]
    }
  ]
}
```

Hope this helps, shout if you need any more help.
