### ISSUE TITLE
Does not use workspace protocol.?

### ISSUE THREAD

**Issue by dhruv-004** [JamieMason/syncpack#85]
## Description
I have a pnpm monorepo, which when using `pnpm add` uses the workspace protocol to use the package
```
project
│   package.json
│
└───shared
│   │   package.json -> "version": "1.0.0"
│
└───website
    │   package.json -> "shared": "workspace^1.0.0"
```

However `syncpack fix-mismatches` updates it to just the version and not using the workspace protocol
Like so
```diff
project
│   package.json
│
└───shared
│   │   package.json -> "version": "1.0.0"
│
└───website
++  │   package.json -> "shared": "1.0.0"
--  │   package.json -> "shared": "workspace^1.0.0"
```

This is my config 
```js
module.exports = {
  dev: true,
  filter: '.',
  indent: '  ',
  overrides: false,
  peer: false,
  pnpmOverrides: true,
  prod: true,
  resolutions: true,
  workspace: true,
  semverGroups: [],
  semverRange: '',
  versionGroups: [
    {
      dependencies: ['**'],
      packages: ['**'],
    },
  ],
};

```

## Help Needed

Am I missing some config, or is this the desired output

**Comment by JamieMason** [comment]
Hey @dhruv-004, 
I think because `workspace: true` is in your config, that `1.0.0` is being read from the `value` prop of `/shared/package.json`. If you set `workspace: false` in your config it will no longer sync that for you and the `workspace:` value will remain. 

I don't see any mention of `workspace:` versions in [semver](https://www.npmjs.com/package/semver)'s issues or code and syncpack doesn't have any special handling of them at the moment. I'm not sure what would happen but I think they'll be treated as invalid.

By the way, are there any changes in behaviour when using a version that matches the local name property vs using `workspace:`? I've not used it myself, I just use a matching version number.

if `workspace:` is valid semver, it might just be that you need to do this? But I'm not sure

```diff
- workspace^1.0.0
+ workspace:^1.0.0
```

or this

```diff
- workspace^1.0.0
+ workspace:*
```

**Comment by dhruv-004** [comment]
Awesome yes, setting `workspace: false` fixed it. Thank you

**Comment by JamieMason** [comment]
Update: [12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0) adds better support for non-semver version formats and there is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide.
